# Unbind the default prefix (Ctrl+b)
unbind C-b

# Set a new prefix (Ctrl+h in your case)
set -g prefix C-h
bind C-h send-prefix

# Reload tmux config with prefix + r
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

